exports.parseOptions = 'declarative: Error parsing options';
exports.verifyDomElement = 'declarative: Invalid DOM element given';
exports.getSingleMapping = 'declarative: Mapping id not existing';
exports.validateMapping = 'declarative: Invalid mapping options';
exports.validateMappingId = 'declarative: Invalid mapping id';
exports.validateMappingTypes = 'declarative: Missing mapping types';
exports.validateMappingTypesFormat = 'declarative: Invalid mapping types';
exports.validateMappingCallback = 'declarative: Invalid mapping callback';
exports.validateMappingMode = 'declarative: Invalid mappingMode';
